[package]
name = "clhorde-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "clhorde-cli"
path = "src/main.rs"

[dependencies]
clhorde-core.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
